### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by kaer1a** [PL7963/Discord-Mica#2]
![image](https://github.com/user-attachments/assets/f957d20c-0da4-404c-9d63-ef358c380680)
![{82450883-E513-46E4-8FDB-CFA4282D5CF6}](https://github.com/user-attachments/assets/0fec2851-f613-4e48-8ec1-5628f887c562)

windows 11 24h2

**Comment by PL7963** [comment]
Resolved 12ff531123f19e04968eee66fb3746100baa5f6c

**Comment by Slluxx** [comment]
Still doesnt work

![Screenshot 2024-12-04 110643](https://github.com/user-attachments/assets/a53653f5-7606-496d-b1ea-68ea85dbd92f)

**Comment by Slluxx** [comment]
NVM, you should have put the requirements into the theme description so we know whats wrong without having to go to your github

**Comment by Slluxx** [comment]
> Does problem solved by restarting or reconfigure MicaForEveryone?
no, it stays the same

> Or does this happen when you enable transparency without my theme? 
Both. It should be a bug with mica unless discord somehow passes through stuff itself
